package jframe;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mariane Martins Curi
 */

import javax.swing.JOptionPane;
import java.text.DecimalFormat;

public class PesoPlanetas extends javax.swing.JFrame {

    /**
     * Creates new form PesoPlaneta
     */
    public PesoPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpPlanetas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtPesoTerra = new javax.swing.JTextField();
        btnCalcularPeso = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        rdoMercurio = new javax.swing.JRadioButton();
        rdoVenus = new javax.swing.JRadioButton();
        rdoMarte = new javax.swing.JRadioButton();
        rdoJupiter = new javax.swing.JRadioButton();
        rdoSaturno = new javax.swing.JRadioButton();
        rdoUrano = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peso na Terra (kg):");

        txtPesoTerra.setText("58");

        btnCalcularPeso.setText("Calcular Peso");
        btnCalcularPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPesoActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o Planeta:");

        grpPlanetas.add(rdoMercurio);
        rdoMercurio.setSelected(true);
        rdoMercurio.setText("Mercúrio");

        grpPlanetas.add(rdoVenus);
        rdoVenus.setText("Vênus");

        grpPlanetas.add(rdoMarte);
        rdoMarte.setText("Marte");

        grpPlanetas.add(rdoJupiter);
        rdoJupiter.setText("Júpiter");

        grpPlanetas.add(rdoSaturno);
        rdoSaturno.setText("Saturno");

        grpPlanetas.add(rdoUrano);
        rdoUrano.setText("Urano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesoTerra, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnCalcularPeso))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoVenus)
                            .addComponent(rdoMercurio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoJupiter)
                            .addComponent(rdoMarte))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoUrano)
                            .addComponent(rdoSaturno))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesoTerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularPeso))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rdoMercurio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rdoVenus))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rdoMarte)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rdoJupiter)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoSaturno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoUrano)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPesoActionPerformed
        // TODO add your handling code here:
        double pesoTerra, pesoPlaneta, gravidade;
        String planeta;
        pesoTerra = Double.parseDouble(txtPesoTerra.getText());
        
        if (rdoMercurio.isSelected()) {
            planeta = "Mercúrio";
            gravidade = 0.37;
        }

        else if (rdoVenus.isSelected()) {
            planeta = "Vênus";
            gravidade = 0.88;
        }

        else if (rdoMarte.isSelected()) {
            planeta = "Marte";
            gravidade = 0.38;
        }

        else if (rdoJupiter.isSelected()) {
            planeta = "Júpiter";
            gravidade = 2.64;
        }

        else if (rdoSaturno.isSelected()) {
            planeta = "Saturno";
            gravidade = 1.15;
        }

        else {
            planeta = "Urano";
            gravidade = 1.17;
        }

        pesoPlaneta = pesoTerra * gravidade;

        DecimalFormat df = new DecimalFormat("#.00");
        JOptionPane.showMessageDialog(rootPane, "O seu peso em " + planeta + " é: " + df.format(pesoPlaneta) + " kg");
    }//GEN-LAST:event_btnCalcularPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesoPlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcularPeso;
    private javax.swing.ButtonGroup grpPlanetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdoJupiter;
    private javax.swing.JRadioButton rdoMarte;
    private javax.swing.JRadioButton rdoMercurio;
    private javax.swing.JRadioButton rdoSaturno;
    private javax.swing.JRadioButton rdoUrano;
    private javax.swing.JRadioButton rdoVenus;
    private javax.swing.JTextField txtPesoTerra;
    // End of variables declaration//GEN-END:variables
}